import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#c0c1ff",
        "on-secondary": "#003824",
        tertiary: "#ffb783",
        "on-primary-fixed": "#07006c",
        "surface-dim": "#13131b",
        outline: "#908fa0",
        "tertiary-fixed": "#ffdcc5",
        "on-tertiary-container": "#452000",
        "on-background": "#e4e1ed",
        primary: "#c0c1ff",
        surface: "#13131b",
        "surface-container-lowest": "#0d0d15",
        secondary: "#4edea3",
        "on-secondary-fixed-variant": "#005236",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#00311f",
        "on-primary-fixed-variant": "#2f2ebe",
        "surface-container-highest": "#34343d",
        "secondary-container": "#00a572",
        "surface-container": "#1f1f27",
        "on-primary-container": "#0d0096",
        "on-secondary-fixed": "#002113",
        "on-tertiary": "#4f2500",
        "surface-bright": "#393841",
        "on-tertiary-fixed-variant": "#703700",
        "inverse-primary": "#494bd6",
        "surface-container-low": "#1b1b23",
        "on-tertiary-fixed": "#301400",
        "outline-variant": "#464554",
        "primary-fixed-dim": "#c0c1ff",
        "tertiary-fixed-dim": "#ffb783",
        "tertiary-container": "#d97721",
        background: "#0a0a0f",
        "on-primary": "#1000a9",
        "on-surface": "#e4e1ed",
        "on-surface-variant": "#c7c4d7",
        "secondary-fixed": "#6ffbbe",
        "secondary-fixed-dim": "#4edea3",
        "error-container": "#93000a",
        "surface-variant": "#34343d",
        error: "#ffb4ab",
        "inverse-on-surface": "#303038",
        "inverse-surface": "#e4e1ed",
        "surface-container-high": "#292932",
        "on-error": "#690005",
        "primary-container": "#8083ff",
        "primary-fixed": "#e1e0ff",
      },
      fontFamily: {
        inter: ["var(--font-inter)", "sans-serif"],
        manrope: ["var(--font-manrope)", "sans-serif"],
        mono: ["var(--font-mono)", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
